name: Update

on:
  push:
    branches: [master]
  schedule:
    - cron: '41 9 */10 * *' # At 09:41 on every 10th day-of-month.

  workflow_dispatch:

jobs:
  Update:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the date
        run: |
          DATE=$(date +'%Y.%m.%d')
          echo "DATE=$DATE" >> $GITHUB_ENV
      - name: Update models.json
        run: |
          swift run update
          git add . || true
      - name: Run tests
        run: swift test
      - name: Push changes (if there are any)
        run: |
          GIT_STATUS="$(git status -s)"
          if [[ $var =~ " M Sources/MacModels/Resources/models.json" ]]; then
              git commit -m "Update made on ${DATE}" || true
              git push origin master || true
              echo "MAKE_RELEASE=1" >> $GITHUB_ENV
          else
              echo "There is nothing to update"
              echo "MAKE_RELEASE=0" >> $GITHUB_ENV
          fi
      - name: Release
        uses: softprops/action-gh-release@9729932bfb75c05ad1f6e3a729294e05abaa7001
        if: env.MAKE_RELEASE == 1
        with:
          target_commitish: master
          tag_name: ${{ env.DATE }}
          body: "Update made on ${{ env.DATE }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
