name: Update

on:
  push:
    branches: [master]
  schedule:
  # Basically runs every time WWDC can be ran
    - cron: '1 * 1 6 *' # At minute 1 on day-of-month 1 in June.
    - cron: '1 * 13 6 *' # At minute 1 on day-of-month 13 in June.
    - cron: '1 * 27 6 *' # At minute 1 on day-of-month 27 in June.
    - cron: '1 * 1 9 *' # At minute 1 on day-of-month 1 in September.
    - cron: '1 * 13 9 *' # At minute 1 on day-of-month 13 in September.
    - cron: '1 * 27 9 *' # At minute 1 on day-of-month 27 in September.

  workflow_dispatch:

jobs:
  Update:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update models.json
        run: swift run update
      - name: Get the date
        run: |
          DATE=$(date +'%Y.%m.%d')
          echo "DATE=$DATE" >> $GITHUB_ENV
      - name: Update repo
        run: |
          rm -rf MacModelDump
          git add . || true
          git commit -m "Update made on ${DATE}" || true
          git push origin master || true
      - name: Release
        uses: softprops/action-gh-release@9729932bfb75c05ad1f6e3a729294e05abaa7001
        with:
          target_commitish: master
          tag_name: ${{ env.DATE }}
          body: "Update made on ${{ env.DATE }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
